apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-httpd-deployment 
  namespace: default
  labels:
    app:  rust-httpd
spec:
  selector:
    matchLabels:
      app: rust-httpd 
  replicas: 1
  template:
    metadata:
      labels:
        app: rust-httpd 
    spec:
      containers:
      - name: rust-httpd 
        image:  localhost/rust-httpd:latest
        imagePullPolicy: Never 
        ports:
        - containerPort: 8000
          name: rust-httpd-svc
---
